# Generated by Django 4.2.17 on 2025-01-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject_id', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='科目番号')),
                ('subject_name', models.CharField(blank=True, max_length=30, null=True, verbose_name='科目名')),
            ],
            options={
                'verbose_name_plural': 'Subject',
            },
        ),
    ]
