# Generated by Django 4.2.17 on 2025-01-03 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attendance_date', models.DateField(blank=True, null=True, verbose_name='遅刻・早退・欠席日')),
                ('attendance_id', models.IntegerField(blank=True, null=True, verbose_name='分類(1:欠席, 2: 遅刻, 3:早退, 4:その他)')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='students.student', verbose_name='学生番号')),
            ],
            options={
                'verbose_name_plural': 'Attendance',
            },
        ),
    ]
